excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://www.saleoffer.biz
title: Techno Skald
tagline: Teknologi Canggih di Era Millenium
description: Blog Manusia Tampan di Indonesia
paginate: 5
