excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://technoskald.github.io
title: Techno Skald
tagline: Teknologi Canggih di Era Millenium
description: Blog Manusia Tampan di Indonesia
paginate: 5
