excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://technoskald.github.io
title: Techno Skald
tagline: Teknologi Canggih di Era Millenium
description: My awesome new site
paginate: 7